# **20230511**

In [2]:
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np


In [3]:
print(pd.__version__)
print(np.__version__)


2.0.1
1.24.3


## 03 넘파이

In [4]:
arr1 = np.array([1,2,3])    
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
arr1 = np.array([[1,2,3],[2,3,4]])    
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(2, 3)


In [6]:
arr1 = np.array([[[1,2,3],[2,3,4]]
                ,[[3,4,5],[4,5,6]]])    
print(type(arr1))
print(arr1.shape)
print(arr1.ndim) # 차원출력

<class 'numpy.ndarray'>
(2, 2, 3)
3


In [7]:
list1 = [1,2,3]
print(type(list1))
arr1 = np.array([list1])
print(type(arr1))
print(arr1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [8]:
list2 = [1,2,'test']
arr2 = np.array([list2])
print(arr2.dtype)

<U11


In [9]:
list3 = [1,2,3.0]
arr3 = np.array(list3)
print(arr3)

[1. 2. 3.]


In [10]:
arr_int = np.array([1,2,3])
print(arr_int.dtype)

arr_float = arr_int.astype('float64')
print(arr_int.dtype, arr_float.dtype)

int32
int32 float64


In [11]:
arr_int8 = arr_float.astype('int8')
print(arr_int8.dtype)

int8


In [12]:
# 서영아 그러니까 술 좀 적당히 마셔
# 너 이제 20살이 아니야
# 알겠니??
# 다음주 목요일까지 간 아껴놔


---

# **20230512**

## 03 넘파이

### ndarray의 차원을 변경하는 reshape()

In [13]:
array1 = np.arange(10)
print('array1 : \n', array1)

array2 = array1.reshape(2,5)
print('array2 : \n',array2,  array2.ndim)

array3 = array1.reshape(5,2)
print('array3 :\n',array3)

# array1.reshape(3,4) => 불가능

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 2
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# 1차원
arr1 = np.arange(1200)

# 2차원
arr2 = arr1.reshape(-1,40)  # 컬럼 40개로 고정, 행은 자동계산 지정 : -1
arr3 = arr1.reshape(40,-1)  # 행 40개 고정

# 3차원
arr4 = arr1.reshape(30,4,10)

print(arr2.shape, arr3.shape,arr4.shape)

(30, 40) (40, 30) (30, 4, 10)


In [15]:
arr1 = np.arange(8)

# 3차원
arr5 = arr1.reshape(2,2,2)
print(arr5)

# 3차원 -> 2차원
arr6 = arr5.reshape(-1,1)
print(arr5,arr6)

print(arr6.tolist()) # .tolist() return => ndarray

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


- list : 아무거나 다 저장, 반복시 for 사용, 비연속 공간 저장 가능
- nadrray : 동일 타입 저장 가능, 브로드캐스팅(for x 반복 가능), 연속 공간 저장

### 넘파이의 ndarray의 데이터 세트 선택하기 - ***인덱싱(indexing)***


1. 단일값 추출(인덱싱) : 원하는 위치의 **인덱스** 값을 지정하면 해당 위치의 데이터가 반환
<br>

2. 슬라이싱 : 슬라이싱은 **연속된** 인덱스상의 ndarray 를 추출하는 방식.
 
    **':'** 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 ndarray 반환
<br>

3. 팬시 인덱싱(**비연속 추출**) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 ndarray 반환
<br>

4. 불린 인덱싱 : **특정 조건에 해당**하는 지 여부인 True/False 값 인덱싱 집합을 기반으로 True 에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

In [16]:
# 1. 단일값 추출

array1 = np.arange(1,10)
print(array1)

print(type(array1[2]), array1[2])

[1 2 3 4 5 6 7 8 9]
<class 'numpy.int32'> 3


In [17]:
array1[-1], array1[-2]

(9, 8)

In [18]:
# 단일 인덱스 사용하여 ndarray내 값 수정


array1[0] = 9
array1[8] = 0

array1

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [19]:
# 2차원에서의 인덱싱

arr1d = np.arange(1,10)
arr2d = arr1d.reshape(3,3)

print(arr2d)
print(arr2d[0,0],arr2d[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 6


In [20]:
# 2. 슬라이싱

arr1 = np.arange(1,10)

print(arr1[1:3],arr1[3:])

[2 3] [4 5 6 7 8 9]


In [21]:
# 2차원에서의 슬라이싱

arr2 = arr1.reshape(3,3)

print(arr2[0:2,1:3])

[[2 3]
 [5 6]]


In [22]:
print(arr2[0])

[1 2 3]


In [23]:
# 3.팬시 인덱싱

print(arr2)

arr3 = arr2[[0,2],2]
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 9]


In [24]:
# 4. 불린 인덱싱

arr1 = np.arange(1,10)

print(arr1,'\n')

print(arr1[arr1>5])

[1 2 3 4 5 6 7 8 9] 

[6 7 8 9]


In [25]:
arr1[[0,8]]

array([1, 9])

In [26]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])

arr3 = arr1[boolean_indexes]
print(arr3)

[6 7 8 9]


In [27]:
indexes = np.array([5,6,7,8])
arr4 = arr1[indexes]
print(arr4)

[6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

- np.sort(data) : function  -> 원본 유지, 정렬된 것 따로 반환
- ndarray.sort() : method   -> 원본 정렬 => return X (None)

#### sort()

In [28]:
# np.sort()

org_array = np.array([3,1,9,5])

#           복사본      ,  원본
print(np.sort(org_array),org_array)

[1 3 5 9] [3 1 9 5]


In [29]:
# ndarray.sort()

# 원본 정렬 -> return X
print(org_array.sort(),org_array)

None [1 3 5 9]


In [30]:
# 내림차순으로 정렬

np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [31]:
# 2차원 행렬 정렬

array2d = np.array([[8,12],[7,1]])

# row 방향(세로)
print(np.sort(array2d, axis=0),'\n')

# column 방향(가로)
print(np.sort(array2d, axis=1))

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


#### argsort()

In [32]:
# 정렬된 행렬의 인덱스 반환하기

org_array = np.array([3,1,9,5])

print(org_array)
print(np.sort(org_array),'\n')
print(type(np.argsort(org_array)),np.argsort(org_array))

[3 1 9 5]
[1 3 5 9] 

<class 'numpy.ndarray'> [1 0 3 2]


In [33]:
#min   max
#[1 3 5 9] 
#[1 0 3 2]
#  median

# => 인덱스에 의미부여 가능

In [34]:
print(np.argsort(org_array)[::-1])

[2 3 0 1]


In [35]:
# 예제 : 성적 1등 학생 '이름' 추출

name_arr =np.array(['Jone','Mike','Sarah','Kate','Samuel'])
score_arr = np.array([78,95,84,98,88])

# 성적 오름차순(min->max) 인덱스
sort_indies_asc = np.argsort(score_arr)

print(sort_indies_asc)
print(name_arr[sort_indies_asc])
print(name_arr[sort_indies_asc][-1])

[0 2 4 1 3]
['Jone' 'Sarah' 'Samuel' 'Mike' 'Kate']
Kate


<br>

### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

a(1,2) , b(3,2) 벡터 

||a|| : 길이

코사인유사도 : ||a|| * ||b|| * cos

내적 값이 클 때 ~ cos값 작을 때 ~ a,b 벡터는 가장 유사하다

=> 내적값이 크다 = 유사도가 크다 => 두 벡터의 방향성이 같다.

:: 내적=유사도

In [36]:
a=np.array([1,2])
b = np.array([3,2])

np.dot(a,b)

7

#### 행렬 내적(행렬 곱)

```python
np.dot(A,B)
```

In [37]:
#(2,3)
A = np.array([[1,2,3],
              [4,5,6]])

#(3,2)
B = np.array([[7,8],
             [9,10],
             [11,12]])

In [38]:
# (2,3)*(3,2) = (2,2)

# [[1*7 + 2*9 + 3*11, 1*8 + 2*10 + 3*12],
#  [4*7 + 5*9 + 6*11, 4*8 + 5*10 + 6*12]]

np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

#### 전치 행렬

```python
np.transpose()
```

In [39]:
C = np.array([[1,2],
              [3,4]])

np.transpose(C)

array([[1, 3],
       [2, 4]])

In [40]:
A = np.array([[1,2,3],
              [4,5,6]])

np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

---

# **20230515**

## 04 데이터 핸들링 - 판다스

### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호변환

#### 1) 데이터 프레임으로 변환

In [42]:
col_name1=['col1']
list1 = [1,2,3]
array1 = np.array(list1)

print(array1.shape)

(3,)


In [43]:
# 리스트를 이용해 DataFrame 생성

df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)

   col1
0     1
1     2
2     3


In [44]:
# 넘파이 ndrrary를 이용해 DataFrame 생성

df_array1 = pd.DataFrame(array1, columns=col_name1)
print(df_array1)

   col1
0     1
1     2
2     3


In [45]:
col_name2 = ['col1','col2','col3']

list2 = [[1,2,3]
         ,[11,12,13]]

array2 = np.array(list2)
print(array2.shape)

(2, 3)


In [46]:
df_list2 = pd.DataFrame(list2,columns=col_name2)
print('list-> DataFrame:\n', df_list2)

list-> DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [47]:
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('array -> DataFrame:\n', df_array2)

array -> DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [48]:
# key는 문자열 컬럼며으로 매핑
# value는 리스트 형 (또는 ndarray) 컬럼 데이터로 매핑

dict={'col1':[1,11],'col2':[2,12],'col3':[3,13]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    12    13


#### 2) 데이터프레임을 변환

In [49]:
# DataFrame -> ndarray

array3 = df_dict.values
print(type(array3),array3.shape)
print(array3)

<class 'numpy.ndarray'> (2, 3)
[[ 1  2  3]
 [11 12 13]]


In [50]:
# DataFrame -> list

list3 = df_dict.values.tolist()
print(type(list3))
print(list3)

<class 'list'>
[[1, 2, 3], [11, 12, 13]]


In [51]:
# DataFrame -> dictionary

#                   value type 지정
dict3 = df_dict.to_dict('list')
print(dict3)

{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}


### DataFrame의 컬럼 데이터 세트 생성과 수정

In [52]:
titanic_df = pd.read_csv('../data/train.csv')

In [53]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [54]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df.head(3)

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0      220.0  
1      0          PC 17599  71.2833   C85        C      0      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0

### DatFrame 데이터 삭제

In [55]:
titanic_drop_df = titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      220.0  
1      0          PC 17599  71.2833   C85        C      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      260.0

### Index 객체(object)

: RDBMS의 PK와 유사하게 DataFrame, Series의 레코드를 고유하게 식별하는 객체

In [56]:
titanic_df = pd.read_csv('../data/train.csv')

# index 객체 추출
indexes = titanic_df.index
print(indexes)

# index 객체를 실제 값 array로 변환
print('Index : ',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index :  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234

Index 객체는 식별성 데이터를 1차원 array로 가지고 있다.

<dr>
또한 ndarray와 유사하게 단일 값 반환 및 슬라이싱으로 가능

In [57]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)       
#print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
6


In [58]:
series_fair = titanic_df['Fare']
print('series.max() : ',series_fair.max())
print('series.sum() : ',series_fair.sum())
print('sum(series)  : ',sum(series_fair))
print('+3           :\n', (series_fair + 3).head(3))

series.max() :  512.3292
series.sum() :  28693.9493
sum(series)  :  28693.949299999967
+3           :
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [59]:
titanic_reset_df = titanic_df.reset_index(inplace=False
                                          #,drop=True #=>index 컬럼 추가되지않음 
                                          )
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass   
0      0            1         0       3  \
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

### 데이터 셀렉션 및 필터링

In [60]:
titanic_df = pd.read_csv('../data/train.csv')

#### DataFrame[]

In [61]:
print('단일 컬럼 데이터 추출:\n',titanic_df['Pclass'].head(3))

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64


In [62]:
print('여러 컬럼의 데이터 추출 : \n', titanic_df[['Survived','Pclass']].head(3))

여러 컬럼의 데이터 추출 : 
    Survived  Pclass
0         0       3
1         1       1
2         1       3


In [63]:
# 인덱스 슬라이싱으로 데이터 추출 가능
titanic_df[0:2]

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [64]:
# 불린 인덱싱
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age   
0            1         0       3   Braund, Mr. Owen Harris    male  22.0  \
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

#### DataFrame.iloc[ , ]    :   index 기반

In [67]:
data = {'Name':['Seoyoung','Sooyeon','Chan','YoonYoung']
        ,'Year':[2011,2016,2015,2015]
        ,'Gender':['Female','Female','Male','Male']
        }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Seoyoung  2011  Female
two      Sooyeon  2016  Female
three       Chan  2015    Male
four   YoonYoung  2015    Male

In [68]:
data_df.iloc[0,0]

'Seoyoung'

In [69]:
print(data_df.iloc[:,-1])

one      Female
two      Female
three      Male
four       Male
Name: Gender, dtype: object


In [70]:
print(data_df.iloc[:,:-1])

            Name  Year
one     Seoyoung  2011
two      Sooyeon  2016
three       Chan  2015
four   YoonYoung  2015


#### DataFrame loc[ , ] : named 기반

In [71]:
data_df.loc['one','Name']

'Seoyoung'

#### 불린 인덱싱

In [72]:
titanic_boolean = titanic_df[titanic_df['Age']>60]
type(titanic_boolean)
titanic_boolean

PassengerId  Survived  Pclass                                       Name   
33            34         0       2                      Wheadon, Mr. Edward H  \
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

In [74]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [75]:
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass                                       Name   
275          276         1       1          Andrews, Miss. Kornelia Theodosia  \
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

### 정렬, Aggrigation 함수, GroupBy 적용

#### DataFrame, Series의 정렬 -  sort_values()

In [76]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass                              Name     Sex   
845          846         0       3               Abbing, Mr. Anthony    male  \
746          747         0       3       Abbott, Mr. Rossmore Edward    male   
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female   

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845  42.0      0      0  C.A. 5547   7.55   NaN        S  
746  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  35.0      1      1  C.A. 2673  20.25   NaN        S

In [77]:
titanic_sorted = titanic_df.sort_values(by=['Pclass','Name']
                                        ,ascending=False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass                             Name   Sex   
868          869         0       3      van Melkebeke, Mr. Philemon  male  \
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
282          283         0       3        de Pelsmaeker, Mr. Alfons  male   

      Age  SibSp  Parch    Ticket  Fare Cabin Embarked  
868   NaN      0      0    345777   9.5   NaN        S  
153  40.5      0      2  A/5. 851  14.5   NaN        S  
282  16.0      0      0    345778   9.5   NaN        S

#### Aggregation 함수 : 집계함수

=> min(),max(),sum(),count() 등

In [78]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [79]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

#### groupby() 적용

In [80]:
titanic_groupby = titanic_df.groupby(by='Pclass')
type(titanic_groupby)

pandas.core.groupby.generic.DataFrameGroupBy

##### 집계함수와 groupby

In [81]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare   
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216  \
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [86]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [87]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [88]:
agg_format = {'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기

#### isna()

In [89]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   
0        False     False   False  False  False  False  False  False   False  \
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [90]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

#### fillna()

In [91]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [92]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### apply lambda 식으로 데이터 가공

: 함수 object 생성

In [93]:
lambda_square = lambda x : x**2

print(lambda_square(3))

9


In [94]:
a = [1,2,3]

squares = map(lambda x :x**2, a)    # map() return map object
list(squares)

[1, 4, 9]